host:
  # web api host
  # you can use API and Web interface through this host
  # webapi: docker.dev.example.net
  webapi: localhost
  reverse_proxy_suffix: localhost

listen:
  # listen address
  # default is only listen from localhost
  foreign_address: 127.0.0.1

  # listen port and reverse proxy port
  http:
    # listen 8080 and transport to container's 5000 port
    - listen: 8080
      target: 80

storage:
  htmldir: ./html

parameters:
  - name: branch
    env: GIT_BRANCH
    rule: ""
    required: true
  # add your custom parameters here!
  # name is parameter name (passed by HTTP parameter)
  # env is environment variable for docker container
  # rule is constraint of value using regexp.
  # required means required or optional parameter (boolean value)

ecs:
  region: ap-northeast-1
  cluster: mirage-ecs-envoy
  launch_type: FARGATE
  default_task_definition: '{{ env "MIRAGE_DEFAULT_TASKDEF" "myapp" }}'
  network_configuration:
    awsvpc_configuration:
      subnets:
        - '{{ env "MIRAGE_SUBNET_1" "subnet-aaaaaa" }}'
      security_groups:
        - '{{ env "MIRAGE_SECURITY_GROUP" "sg-111111" }}'
      assign_public_ip: ENABLED
